services:
  db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotlight
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data: